# Evaluation Notebook — LangGraph RAG vs Baseline

Task 5: run ≥20 questions through the graph system and the simple baseline, then label accuracy and compare.

In [1]:
import sys
from pathlib import Path

import pandas as pd

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))

from src.pipeline import ingest_and_index
from src.graph.runner import run_rag
from src.graph.builder import build_graph, export_graph_mermaid
from src.generation.chains import run_baseline
from tests.evaluation.questions import SAMPLE_QUESTIONS
from tests.evaluation.metrics import run_eval_suite, summarize_comparison

print("ROOT =", ROOT)
print("Questions available:", len(SAMPLE_QUESTIONS))

ROOT = c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System
Questions available: 20

## 0. Index corpus (skip if already built)

In [ ]:
# ingest_and_index()

## 1. Graph visualization (Task 6)

In [2]:
graph = build_graph()
mmd = export_graph_mermaid(graph)
assets = ROOT / "assets"
assets.mkdir(exist_ok=True)
(assets / "graph.mmd").write_text(mmd, encoding="utf-8")
print(mmd)

---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	query_analyser(query_analyser)
	query_rewriter(query_rewriter)
	retriever(retriever)
	relevance_grader(relevance_grader)
	answer_generator(answer_generator)
	hallucination_checker(hallucination_checker)
	__end__([<p>__end__</p>]):::last
	__start__ --> query_analyser;
	answer_generator --> hallucination_checker;
	hallucination_checker -. &nbsp;end&nbsp; .-> __end__;
	hallucination_checker -.-> answer_generator;
	query_analyser --> query_rewriter;
	query_rewriter --> retriever;
	relevance_grader -.-> answer_generator;
	relevance_grader -.-> retriever;
	retriever --> relevance_grader;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

## 2. Run evaluation (≥20 questions)

In [3]:
questions = SAMPLE_QUESTIONS  # replace with mentor questions when available
assert len(questions) >= 20

# Pause between questions to reduce Gemini free-tier 503 / rate-limit failures.
# Checkpoints are saved after every question so a crash does not lose progress.
TRACE_DIR = ROOT / "data" / "traces"
TRACE_DIR.mkdir(parents=True, exist_ok=True)

df_graph = run_eval_suite(
    questions,
    lambda q: run_rag(q),
    "langgraph",
    pause_seconds=4.0,
    checkpoint_path=TRACE_DIR / "eval_langgraph_checkpoint.csv",
)
df_base = run_eval_suite(
    questions,
    lambda q: run_baseline(q),
    "baseline",
    pause_seconds=3.0,
    checkpoint_path=TRACE_DIR / "eval_baseline_checkpoint.csv",
)
df = pd.concat([df_graph, df_base], ignore_index=True)
df.to_csv(TRACE_DIR / "eval_results.csv", index=False)
print("Saved", TRACE_DIR / "eval_results.csv")
print("Failures:", (df["error"].astype(str).str.len() > 0).sum())
df.head()

[langgraph] Resuming from checkpoint 'eval_langgraph_checkpoint.csv'. Already completed 8 / 20 questions.
[langgraph] (1/20) [SKIP - Already Completed] What is Retrieval-Augmented Generation?...
[langgraph] (2/20) [SKIP - Already Completed] Why do linear RAG pipelines fail on complex questions?...
[langgraph] (3/20) [SKIP - Already Completed] How does LangGraph help build stateful multi-agent RAG syste...
[langgraph] (4/20) [SKIP - Already Completed] What are the four query types used in research assistants?...
[langgraph] (5/20) [SKIP - Already Completed] Explain multi-query retrieval and why it improves recall....
[langgraph] (6/20) [SKIP - Already Completed] What does a relevance grader do in a RAG graph?...
[langgraph] (7/20) [SKIP - Already Completed] How does a hallucination checker improve answer faithfulness...
[langgraph] (8/20) [SKIP - Already Completed] What evaluation metrics are recommended for comparing RAG sy...
[langgraph] (9/20) Running: What is parent-document retrieval?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.2524109179376477), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.23643776811420103), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.1388810479219138), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.11417549255549497), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.1389646330408172)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.2524109179376477), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.23643776811420103), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.1388810479219138), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.11417549255549497), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.1389646330408172)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (133.5s) | retries: r=1, g=0
[langgraph] (10/20) Running: What is step-back prompting?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.03972704646476066), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.03969919531620136), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.04232393245406563), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.16837276517668753), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.18593839152426983)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.03972704646476066), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.03969919531620136), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.04232393245406563), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.16837276517668753), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.18593839152426983)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (36.4s) | retries: r=1, g=0
[langgraph] (11/20) Running: Compare factual and multi-hop research questions....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.11411749849194397), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.07256239173414292), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.032443025289171645), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.07336247327773138), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.269551416942607)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.1812342474031171), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.10503805579833314), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.0701397566531945), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.07182773793605568), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.1852337805108648)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (19.9s) | retries: r=0, g=0
[langgraph] (12/20) Running: What recovery loops can a LangGraph RAG system implement?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (16.6s) | retries: r=1, g=0
[langgraph] (13/20) Running: How should baseline and graph systems be compared fairly?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.32470658730014257), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.03597370101747155), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.025863143593347848), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.05594183208902659), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.16122010780960072)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.18902045619701968), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.02492571338876859), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.10994045869488112), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.1694017383362325), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.3096863434929851)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 3/4). Retrying in 8s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (28.8s) | retries: r=0, g=0
[langgraph] (14/20) Running: What information should a state transition log include?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.07292603474309489), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.1056027893398368), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.11135929020315172), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.1755267712429267), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.2245516482560106)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (9.2s) | retries: r=0, g=0
[langgraph] (15/20) Running: Why is typed shared state important in multi-agent graphs?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.2519504214708177), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.030919753890291002), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.17294291654811778), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.20007149423542803), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.20505906799451012)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (8.7s) | retries: r=0, g=0
[langgraph] (16/20) Running: When should a system answer that it cannot answer from documents?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 3/4). Retrying in 8s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 4/4). Retrying in 16s...
[llm] Giving up on gemini-3.5-flash-lite; trying next fallback model...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.07744797011982874), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.02674927316498321), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.006310749035504326), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.11482645854905194), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.1928084121252427)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.07744797011982874), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.02674927316498321), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.006310749035504326), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.11482645854905194), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.1928084121252427)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (58.8s) | retries: r=1, g=0
[langgraph] (17/20) Running: What happens when retrieval quality is below a threshold?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.4198803668244724), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.2115435634538474), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.06426713330392575), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.004490932410500914), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.16426884224348481)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (11.7s) | retries: r=0, g=0
[langgraph] (18/20) Running: What happens when unsupported claims are found in an answer?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.015235815741325931), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.11308326489464138), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.19938778805888413), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.23986705436159617), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.3069682089388204)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (11.6s) | retries: r=0, g=0
[langgraph] (19/20) Running: Name one limitation of retrieve-then-generate pipelines....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.14453327748201272), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.06420312015934404), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.14834871315546483), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.15576284957071307), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.19154080350942904)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (16.1s) | retries: r=0, g=0
[langgraph] (20/20) Running: How does multi-query retrieval merge results?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.43403837832310044), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.20714764715416123), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.11737207813395523), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.13902549309006695), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.15509810947599934)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (27.9s) | retries: r=0, g=0
[langgraph] Checkpoint updated at: c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\data\traces\eval_langgraph_checkpoint.csv
[baseline] (1/20) Running: What is Retrieval-Augmented Generation?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.5574221815206815), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.34943009722402707), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.15223156794992154), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.04218344908967264), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.036065631212380156)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (17.4s) | retries: r=0, g=0
[baseline] (2/20) Running: Why do linear RAG pipelines fail on complex questions?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.14507107126901175), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.12242792978762507), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.026662163547417572), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.1138097079755751), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.4070168194024657)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (2.7s) | retries: r=0, g=0
[baseline] (3/20) Running: How does LangGraph help build stateful multi-agent RAG systems?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (2.6s) | retries: r=0, g=0
[baseline] (4/20) Running: What are the four query types used in research assistants?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.45783491046083635), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.20508059711579285), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.15098385264660508), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.06811131312806218), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.09212667170326672)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (5.0s) | retries: r=0, g=0
[baseline] (5/20) Running: Explain multi-query retrieval and why it improves recall....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.5243707915058324), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.30418848992067515), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.29813308360772095), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.03700073542198501), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.15407663845548925)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (3.3s) | retries: r=0, g=0
[baseline] (6/20) Running: What does a relevance grader do in a RAG graph?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.32081183917609934), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.2950284624527114), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.21730132872261765), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.17349246138754504), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.019453450871811162)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (2.5s) | retries: r=0, g=0
[baseline] (7/20) Running: How does a hallucination checker improve answer faithfulness?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.08848142500410161), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.08303006732400553), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.005546289497213697), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.059886102760070115), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.14984062729905334)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> FAIL (49.5s) | [WinError 10051] A socket operation was attempted to an unreachable network
[baseline] (8/20) Running: What evaluation metrics are recommended for comparing RAG systems?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.6458344685789541), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.176749654134164), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.05855876414161021), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.05836257848009829), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.25358897241868195)]
  results = store.similarity_search_with_relevance_scores(

  -> FAIL (0.9s) | [Errno 11001] getaddrinfo failed

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[baseline] (9/20) Running: What is parent-document retrieval?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.2586703149973947), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.25530244462658613), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.11649247340553281), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.10846956791039308), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.164683314351741)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (3.0s) | retries: r=0, g=0
[baseline] (10/20) Running: What is step-back prompting?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.010877022896871535), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.0002091998417370622), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.0874809931793048), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.14793306093545033), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.2526970608104946)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (9.0s) | retries: r=0, g=0
[baseline] (11/20) Running: Compare factual and multi-hop research questions....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.27418372699728455), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.20859581286899553), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.12889797679622939), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.10794559828970562), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.17420344449338154)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (3.8s) | retries: r=0, g=0
[baseline] (12/20) Running: What recovery loops can a LangGraph RAG system implement?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (9.9s) | retries: r=0, g=0
[baseline] (13/20) Running: How should baseline and graph systems be compared fairly?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.2027424585478026), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.004796294246268706), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.10260850863422899), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.2113553856935526), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.24889170615214296)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (80.7s) | retries: r=0, g=0
[baseline] (14/20) Running: What information should a state transition log include?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.16815313003079102), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.07185850513546876), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.15006805169361814), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.1770464180128355), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.18846349351225444)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (2.5s) | retries: r=0, g=0
[baseline] (15/20) Running: Why is typed shared state important in multi-agent graphs?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.23747584499302432), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.08356630959591604), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.24326999091036572), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.2850152642486481), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.2923392064080832)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (24.0s) | retries: r=0, g=0
[baseline] (16/20) Running: When should a system answer that it cannot answer from documents?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.034033260112029895), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.11208168718662859), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.14935340973026756), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.24175152425221524), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.2734448585143463)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (3.5s) | retries: r=0, g=0
[baseline] (17/20) Running: What happens when retrieval quality is below a threshold?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.3236911854258181), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.17333053319556624), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.07113167481459204), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.08056402098909099), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.11523528297960772)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (2.7s) | retries: r=0, g=0
[baseline] (18/20) Running: What happens when unsupported claims are found in an answer?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.059896723765894944), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.20306240319315494), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.35055850271751554), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.3546464098482842), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.36538795565977056)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (2.8s) | retries: r=0, g=0
[baseline] (19/20) Running: Name one limitation of retrieve-then-generate pipelines....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.13022939574068848), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.04973006096809707), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.1343943973756898), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.14702639793028394), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.16888198340039606)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (4.8s) | retries: r=0, g=0
[baseline] (20/20) Running: How does multi-query retrieval merge results?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.519746102112429), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.2223733647661157), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.21877857576292448), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.07597540929801294), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.09515062379022621)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (3.5s) | retries: r=0, g=0
[baseline] Checkpoint updated at: c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\data\traces\eval_baseline_checkpoint.csv
Saved c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\data\traces\eval_results.csv
Failures: 2

,question,system,answer,accuracy,retry_triggered,retrieval_retries,generation_retries,hallucination_flagged,latency_seconds,error
0,What is Retrieval-Augmented Generation?,langgraph,"Based on the provided document, Retrieval-Augm...",NaN,False,0,0,False,31.845,NaN
1,Why do linear RAG pipelines fail on complex qu...,langgraph,"Based on the provided context, linear RAG pipe...",NaN,False,0,0,False,15.570,NaN
2,How does LangGraph help build stateful multi-a...,langgraph,"Based on the provided context, LangGraph helps...",NaN,False,0,0,False,18.337,NaN
3,What are the four query types used in research...,langgraph,"Based on the provided document, the four query...",NaN,False,0,0,False,15.917,NaN
4,Explain multi-query retrieval and why it impro...,langgraph,"Based on the provided documents, multi-query r...",NaN,False,0,0,False,16.184,NaN

## 3. Label accuracy manually

Set each row's `accuracy` to one of: `correct`, `partially_correct`, `incorrect`, `hallucinated`, `unable_to_answer`.

In [4]:
# Export for labeling (also already saved by the eval cell)
out = ROOT / "data" / "traces" / "eval_results.csv"
df.to_csv(out, index=False)
print("Wrote", out)

# After you fill the accuracy column in the CSV (or here), summarize:
# df = pd.read_csv(out)
# summarize_comparison(df)

Wrote c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\data\traces\eval_results.csv

## 4. Multi-query vs plain similarity (Task 3, ≥15 questions)

In [5]:
subset = questions[:15]
df_mq = run_eval_suite(
    subset,
    lambda q: run_rag(q, use_multi_query=True),
    "multi_query",
    pause_seconds=4.0,
    checkpoint_path=TRACE_DIR / "eval_mq_checkpoint.csv",
)
df_plain = run_eval_suite(
    subset,
    lambda q: run_rag(q, use_multi_query=False),
    "plain_similarity",
    pause_seconds=4.0,
    checkpoint_path=TRACE_DIR / "eval_plain_checkpoint.csv",
)
df_enh = pd.concat([df_mq, df_plain], ignore_index=True)
df_enh.to_csv(TRACE_DIR / "eval_enhancement.csv", index=False)
df_enh[["question", "system", "latency_seconds", "retrieval_retries", "error"]].head(10)

[multi_query] (1/15) Running: What is Retrieval-Augmented Generation?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.5376371864242124), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.34213810237576325), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.18688774136867148), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.10390236681835852), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.06290525010629944)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (11.9s) | retries: r=0, g=0
[multi_query] (2/15) Running: Why do linear RAG pipelines fail on complex questions?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.09862760443352314), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.09014580405179684), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.07297025470548912), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.15648726960291848), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.3801315976184576)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (33.3s) | retries: r=0, g=0
[multi_query] (3/15) Running: How does LangGraph help build stateful multi-agent RAG systems?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.23152985189880448), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.12813655183103156), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.11908876933895862), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.22110959943182285), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.2788399080048318)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (8.6s) | retries: r=0, g=0
[multi_query] (4/15) Running: What are the four query types used in research assistants?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.46687507229163494), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.20448261762912034), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.13379813799149998), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.09416354459810106), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.1354621456358649)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (20.2s) | retries: r=0, g=0
[multi_query] (5/15) Running: Explain multi-query retrieval and why it improves recall....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.5089843258136573), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.29102560766223784), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.24197223937956058), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.09123239987156251), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.12937496059913345)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.6174850652776773), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.36690333767967354), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.2763319518658848), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.05559600927868846), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.06173601223491021)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (11.2s) | retries: r=0, g=0
[multi_query] (6/15) Running: What does a relevance grader do in a RAG graph?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.27732923059534953), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.22242469962760192), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.10880859715981472), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.055317671491122544), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.13461457251231068)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (18.8s) | retries: r=0, g=0
[multi_query] (7/15) Running: How does a hallucination checker improve answer faithfulness?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.14747900501813616), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.07949251374109212), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.021162624101167204), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.04104924316770231), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.12303801333812658)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 3/4). Retrying in 8s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (36.5s) | retries: r=0, g=0
[multi_query] (8/15) Running: What evaluation metrics are recommended for comparing RAG systems?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.5798980000134799), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.1571402428085914), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.04620257256367144), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.08669419581130344), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.2935467136179202)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (35.8s) | retries: r=0, g=0
[multi_query] (9/15) Running: What is parent-document retrieval?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.2524109179376477), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.23643776811420103), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.1388810479219138), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.11417549255549497), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.1389646330408172)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.2524109179376477), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.23643776811420103), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.1388810479219138), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.11417549255549497), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.1389646330408172)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (13.3s) | retries: r=1, g=0
[multi_query] (10/15) Running: What is step-back prompting?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.03972704646476066), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.03969919531620136), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.04232393245406563), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.16837276517668753), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.18593839152426983)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.03972704646476066), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.03969919531620136), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.04232393245406563), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.16837276517668753), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.18593839152426983)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (10.9s) | retries: r=1, g=0
[multi_query] (11/15) Running: Compare factual and multi-hop research questions....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 3/4). Retrying in 8s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 4/4). Retrying in 16s...
[llm] Giving up on gemini-3.5-flash-lite; trying next fallback model...
[llm] gemini-3.8-flash busy/unavailable (attempt 1/4). Retrying in 2s...
[llm] gemini-3.8-flash busy/unavailable (attempt 2/4). Retrying in 4s...
[llm] gemini-3.8-flash busy/unavailable (attempt 3/4). Retrying in 8s...
  -> FAIL (84.5s) | [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1032)
[multi_query] (12/15) Running: What recovery loops can a LangGraph RAG system implement?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (9.9s) | retries: r=0, g=0
[multi_query] (13/15) Running: How should baseline and graph systems be compared fairly?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.4100622163170111), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.3261606114269199), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.19190338492886183), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.07067396003976378), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.12816669474602316)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.133380294135363), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.06919570147509269), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.08707478185335682), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.22791142643190487), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.2837018841553516)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (8.7s) | retries: r=0, g=0
[multi_query] (14/15) Running: What information should a state transition log include?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.075290304357162), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.12965810312742976), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.1625009505358468), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.20117717465926277), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.21556661450306414)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 3/4). Retrying in 8s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 4/4). Retrying in 16s...
[llm] Giving up on gemini-3.5-flash-lite; trying next fallback model...
[llm] gemini-3.8-flash busy/unavailable (attempt 1/4). Retrying in 2s...
[llm] gemini-3.8-flash busy/unavailable (attempt 2/4). Retrying in 4s...
[llm] gemini-3.8-flash busy/unavailable (attempt 3/4). Retrying in 8s...
[llm] gemini-3.8-flash busy/unavailable (attempt 4/4). Retrying in 16s...
[llm] Giving up on gemini-3.8-flash; trying next fallback model...
[llm] Model gemini-2.5-flash not available. Trying next fallback...
  -> FAIL (74.3s) | All Gemini models failed (overloaded or unavailable). Wait 1–2 minutes and retry, or change GEMINI_CHAT_MODEL in .env (try gemini-3.5-flash-lite or gemini-3.8-flash).
[multi_query] (15/15) Running: Why is typed shared state important in multi-agent graphs?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.2519504214708177), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.030919753890291002), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.17294291654811778), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.20007149423542803), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.20505906799451012)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.2519504214708177), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.030919753890291002), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.17294291654811778), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.20007149423542803), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.20505906799451012)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (13.8s) | retries: r=1, g=0
[multi_query] Checkpoint updated at: c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\data\traces\eval_mq_checkpoint.csv
[plain_similarity] (1/15) Running: What is Retrieval-Augmented Generation?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (8.8s) | retries: r=0, g=0
[plain_similarity] (2/15) Running: Why do linear RAG pipelines fail on complex questions?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.08498998007345915), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.05836101112839709), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.06396456899677228), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.12167043239764497), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.2971739556944648)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (8.5s) | retries: r=0, g=0
[plain_similarity] (3/15) Running: How does LangGraph help build stateful multi-agent RAG systems?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.18519520822617097), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.11463843353953862), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.10294947663868204), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.24005663088619822), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.28183233424910537)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 3/4). Retrying in 8s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 4/4). Retrying in 16s...
[llm] Giving up on gemini-3.5-flash-lite; trying next fallback model...
[llm] gemini-3.8-flash busy/unavailable (attempt 1/4). Retrying in 2s...
[llm] gemini-3.8-flash busy/unavailable (attempt 2/4). Retrying in 4s...
[llm] gemini-3.8-flash busy/unavailable (attempt 3/4). Retrying in 8s...
[llm] gemini-3.8-flash busy/unavailable (attempt 4/4). Retrying in 16s...
[llm] Giving up on gemini-3.8-flash; trying next fallback model...
[llm] Model gemini-2.5-flash not available. Trying next fallback...
  -> FAIL (81.9s) | All Gemini models failed (overloaded or unavailable). Wait 1–2 minutes and retry, or change GEMINI_CHAT_MODEL in .env (try gemini-3.5-flash-lite or gemini-3.8-flash).
[plain_similarity] (4/15) Running: What are the four query types used in research assistants?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.46687507229163494), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.20448261762912034), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.13379813799149998), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.09416354459810106), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.1354621456358649)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (11.5s) | retries: r=0, g=0
[plain_similarity] (5/15) Running: Explain multi-query retrieval and why it improves recall....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.5089843258136573), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.29102560766223784), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.24197223937956058), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.09123239987156251), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.12937496059913345)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (13.2s) | retries: r=0, g=0
[plain_similarity] (6/15) Running: What does a relevance grader do in a RAG graph?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.27732923059534953), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.22242469962760192), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.10880859715981472), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.055317671491122544), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.13461457251231068)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (8.1s) | retries: r=0, g=0
[plain_similarity] (7/15) Running: How does a hallucination checker improve answer faithfulness?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.13634675792095374), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.13274109503084675), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.043983709576966956), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.009669852861822537), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.1113045835937847)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 3/4). Retrying in 8s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 4/4). Retrying in 16s...
[llm] Giving up on gemini-3.5-flash-lite; trying next fallback model...
[llm] gemini-3.8-flash busy/unavailable (attempt 1/4). Retrying in 2s...
[llm] gemini-3.8-flash busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (52.1s) | retries: r=0, g=0
[plain_similarity] (8/15) Running: What evaluation metrics are recommended for comparing RAG systems?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.586374706224149), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.16324942850024549), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.06482052142487382), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.06580562763342512), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.2565588922458506)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (12.1s) | retries: r=0, g=0
[plain_similarity] (9/15) Running: What is parent-document retrieval?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.2737008927007437), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.26605621302414073), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.17788020119862025), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.0940209538912824), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.08837593936058519)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.2737008927007437), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.26605621302414073), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.17788020119862025), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.0940209538912824), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.08837593936058519)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (12.9s) | retries: r=1, g=0
[plain_similarity] (10/15) Running: What is step-back prompting?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.1833333290463537), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.1701486990140848), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.0009229488029626198), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.04592276755471403), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.05629611849760918)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.1833333290463537), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.1701486990140848), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.0009229488029626198), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.04592276755471403), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.05629611849760918)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (38.2s) | retries: r=1, g=0
[plain_similarity] (11/15) Running: Compare factual and multi-hop research questions....

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), 0.08793570760958258), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'chunk_id': 1, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), 0.058765367993010686), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.06747675017688204), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.07012197068312287), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.28397364703454975)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (25.8s) | retries: r=0, g=0
[plain_similarity] (12/15) Running: What recovery loops can a LangGraph RAG system implement?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (7.6s) | retries: r=0, g=0
[plain_similarity] (13/15) Running: How should baseline and graph systems be compared fairly?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), 0.37993501679869646), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 3, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), 0.015002525016511892), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.08806961606560804), (Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'chunk_id': 0, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), -0.22635747212730828), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'chunk_id': 2, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.2632027528577139)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (14.9s) | retries: r=0, g=0
[plain_similarity] (14/15) Running: What information should a state transition log include?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\src\retrieval\retriever.py:29: UserWarning: Relevance scores must be between 0 and 1, got [(Document(id='603686f6-0961-4a51-8bf6-3cd7a1c37d02', metadata={'chunk_id': 0, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\langgraph_notes.md'}, page_content='# LangGraph Checkpointing Notes\n\nLangGraph supports checkpointing so graph state can be inspected after each node.\nMemorySaver stores checkpoints in process memory. For durable runs, a SQLite\ncheckpointer can persist state to disk. State transition logs should record the\nnode name, UTC timestamp, and a short summary of fields that changed.\n\n## Parent Document Retrieval (optional technique)\n\nParent-document retrieval embeds small child chunks for precise search, but\nreturns larger parent passages to the generator so answers have fuller context.\n\n## Step-Back Prompting (optional technique)\n\nStep-back prompting first retrieves broader background context, then retrieves\nspecific details, and combines both before generation.'), 0.07292603474309489), (Document(id='7e8e3c3b-12fd-4174-ba4b-6c326b214686', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 2, 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## LangGraph for Stateful Multi-Agent RAG\n\nLangGraph lets developers build graphs of specialized nodes that share a typed\nstate. Conditional edges can route execution based on intermediate results.\nCycles enable recovery loops such as re-retrieving when relevance is low, or\nregenerating when hallucinations are detected.\n\n## Query Types in Research Assistants\n\nResearch questions are often classified as:\n- Factual: a single fact can answer the question.\n- Multi-hop: information must be combined across passages.\n- Comparative: two or more entities or concepts are compared.\n- Unanswerable: the corpus does not contain enough information.\n\n## Multi-Query Retrieval'), -0.1056027893398368), (Document(id='aa9ce36e-db29-4871-8333-2d5edc6249bb', metadata={'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 1}, page_content='# Sample Research Corpus — AI Safety & RAG Systems\n\n## What is Retrieval-Augmented Generation?\n\nRetrieval-Augmented Generation (RAG) combines a retriever with a generator.\nThe retriever finds relevant passages from a document corpus. The generator\n(usually a large language model) produces an answer grounded in those passages.\nRAG reduces hallucinations compared to asking an LLM with no external context.\n\n## Limitations of Linear RAG Pipelines\n\nA simple retrieve-then-generate pipeline can fail when:\n1. The retrieved passages are irrelevant to the question.\n2. The model invents facts that are not present in the context.\n3. Multi-hop questions require combining evidence from multiple documents.\n4. There is no recovery mechanism when retrieval quality is poor.'), -0.11135929020315172), (Document(id='2cd3d867-17da-48dc-a5ce-761302ca28e6', metadata={'chunk_id': 3, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Multi-Query Retrieval\n\nMulti-query retrieval generates several rephrasings of the user question,\nretrieves documents for each rephrasing, then merges and deduplicates results.\nThis improves recall when wording mismatch would otherwise hide relevant text.\n\n## Relevance Grading and Hallucination Checking\n\nA relevance grader scores each retrieved chunk against the original question.\nIf average relevance falls below a threshold, the system can retry retrieval.\nA hallucination checker verifies that claims in the generated answer are\nsupported by the retrieved context. Unsupported claims trigger regeneration.\n\n## Evaluation Metrics for RAG Systems'), -0.1755267712429267), (Document(id='8cde21c3-f016-4ba1-b168-a31e56a6cc91', metadata={'source': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md', 'chunk_id': 4, 'file_path': 'C:\\Users\\manickam.s\\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\\Documents\\Multi-Agent_RAG_System\\data\\raw\\sample_corpus.md'}, page_content='## Evaluation Metrics for RAG Systems\n\nCommon evaluation dimensions include answer correctness, hallucination rate,\nwhether retry loops were triggered, and end-to-end latency. Fair comparisons\nshould use the same corpus, embedding model, and test questions for both the\nbaseline pipeline and the graph-based system.'), -0.2245516482560106)]
  results = store.similarity_search_with_relevance_scores(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 1/4). Retrying in 2s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 2/4). Retrying in 4s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[llm] gemini-3.5-flash-lite busy/unavailable (attempt 3/4). Retrying in 8s...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> OK (24.5s) | retries: r=0, g=0
[plain_similarity] (15/15) Running: Why is typed shared state important in multi-agent graphs?...

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

  -> FAIL (100.2s) | [WinError 10053] An established connection was aborted by the software in your host machine
[plain_similarity] Checkpoint updated at: c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\data\traces\eval_plain_checkpoint.csv

,question,system,latency_seconds,retrieval_retries,error
0,What is Retrieval-Augmented Generation?,multi_query,11.885,0,
1,Why do linear RAG pipelines fail on complex qu...,multi_query,33.325,0,
2,How does LangGraph help build stateful multi-a...,multi_query,8.608,0,
3,What are the four query types used in research...,multi_query,20.197,0,
4,Explain multi-query retrieval and why it impro...,multi_query,11.202,0,
5,What does a relevance grader do in a RAG graph?,multi_query,18.808,0,
6,How does a hallucination checker improve answe...,multi_query,36.541,0,
7,What evaluation metrics are recommended for co...,multi_query,35.781,0,
8,What is parent-document retrieval?,multi_query,13.270,1,
9,What is step-back prompting?,multi_query,10.912,1,

## 5. Save one complex state trace (Task 4)

In [ ]:
# At the top of cell 5, add a fresh import guard:
import importlib, src.graph.runner
importlib.reload(src.graph.runner)

complex_q = "Compare factual and multi-hop questions and explain how recovery loops help RAG."
trace = run_rag(complex_q, save_trace=True, trace_name="complex_query_trace")
print(trace["final_answer"][:500])
print("Trace:", trace.get("trace_path"))

c:\Users\manickam.s\OneDrive - InTimeTec Visionsoft Pvt. Ltd.,\Documents\Multi-Agent_RAG_System\.venv\Lib\site-packages\langchain_google_genai\chat_models.py:3908: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

ConnectError: [Errno 11001] getaddrinfo failed